export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED', 
			 USER_FETCH_FAILED = 'USER_FETCH_FAILED', 
			 USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED',
			 USER_GET_SUCCEEDED = 'USER_GET_SUCCEEDED';
